import { WebsiteShowcaseItem } from '../types';

export const SHOWCASE_DATA: WebsiteShowcaseItem[] = [
  {
    id: 'restaurant',
    title: 'The Rustic Table & Bar',
    category: 'Restaurant & Hospitality',
    tagline: 'Artisanal Italian Dining & Wood-Fired Kitchen',
    description: 'A mouthwatering, mobile-friendly restaurant website featuring digital interactive menu, 1-click table reservations, WhatsApp orders, and Google Reviews integration.',
    accentColor: '#F97316',
    gradient: 'from-amber-500/20 via-orange-500/10 to-rose-500/20',
    features: ['Instant Table Booking', 'Digital WhatsApp Ordering', 'Dynamic Daily Specials', 'Chef Gallery & VIP Club'],
    metrics: [
      { label: 'Booking Rate', value: '+140%' },
      { label: 'Mobile Traffic', value: '88%' },
      { label: 'Google Search Rank', value: '#1 Local' },
    ],
    heroImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&auto=format&fit=crop&q=80',
    desktopMockup: {
      heroTitle: 'Handcrafted Italian Dining with Authentic Passion',
      heroSubtitle: 'Fresh farm-to-table pastas, artisan wood-fired pizzas, and sommelier-curated wines in the heart of downtown.',
      badge: 'Michelin Guide Recommended • Downtown',
      navItems: ['Menu', 'Reservations', 'Private Dining', 'Story', 'Contact'],
      ctaText: 'Reserve a Table',
      heroBg: 'bg-gradient-to-br from-amber-950/80 via-stone-900 to-black',
      cards: [
        {
          title: 'Truffle Tagliolini',
          desc: 'Fresh handmade egg pasta, black summer truffles, 24-month aged Parmigiano.',
          icon: 'Utensils',
          meta: '₹480',
        },
        {
          title: 'Wood-Fired Margherita',
          desc: 'San Marzano D.O.P., fior di latte, fresh organic basil, cold-pressed olive oil.',
          icon: 'Flame',
          meta: '₹390',
        },
        {
          title: 'Private Cellar Events',
          desc: 'Bespoke 5-course tasting menus paired with rare vintage regional wines.',
          icon: 'Wine',
          meta: 'Up to 24 Guests',
        },
      ],
    },
  },
  {
    id: 'salon',
    title: 'Aura Luxe Hair & Aesthetics',
    category: 'Salon & Wellness Spa',
    tagline: 'Luxury Hair Styling & Advanced Skin Therapy',
    description: 'A sophisticated, high-converting salon website with real-time stylist availability, transparent price cards, bridal packages, and Instagram showcase feed.',
    accentColor: '#EC4899',
    gradient: 'from-pink-500/20 via-purple-500/10 to-indigo-500/20',
    features: ['24/7 Appointment Booking', 'Stylist Portfolios', 'Treatment Price Calculator', 'WhatsApp VIP Consultations'],
    metrics: [
      { label: 'No-Show Reduction', value: '-65%' },
      { label: 'New Client Bookings', value: '4.8x' },
      { label: 'Average Ticket Value', value: '+₹1,800' },
    ],
    heroImage: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1200&auto=format&fit=crop&q=80',
    desktopMockup: {
      heroTitle: 'Elevate Your Natural Radiance & Signature Style',
      heroSubtitle: 'Award-winning master colorists, precision haircuts, and restorative dermatological facial therapies.',
      badge: 'Voted Best Luxury Salon 2025',
      navItems: ['Services', 'Master Stylists', 'Bridal', 'Lookbook', 'Book Online'],
      ctaText: 'Book Treatment',
      heroBg: 'bg-gradient-to-br from-pink-950/70 via-slate-900 to-black',
      cards: [
        {
          title: 'Balayage & Color Melt',
          desc: 'Customized dimensional tone blending with bond-building Olaplex therapy.',
          icon: 'Sparkles',
          meta: 'From ₹2,499',
        },
        {
          title: 'Hydra-Facial Infusion',
          desc: 'Deep ultrasonic pore cleansing, peptide hydration, and LED light therapy.',
          icon: 'Heart',
          meta: '60 Min • ₹1,999',
        },
        {
          title: 'Bridal Beauty Suite',
          desc: 'Complete bridal hair, bespoke airbrush makeup, and champagne bridal lounge.',
          icon: 'Crown',
          meta: 'Custom Packages',
        },
      ],
    },
  },
  {
    id: 'realestate',
    title: 'Apex Horizon Real Estate',
    category: 'Real Estate & Properties',
    tagline: 'Luxury Waterfront Villas & Modern Urban Penthouses',
    description: 'High-impact property developer and agency portal with immersive video tours, interactive floor plans, neighborhood guides, and instant buyer inquiry forms.',
    accentColor: '#06B6D4',
    gradient: 'from-cyan-500/20 via-blue-500/10 to-sky-500/20',
    features: ['Interactive Property Search', '3D Virtual Tour Viewer', 'Mortgage & ROI Calculator', 'Instant Agent WhatsApp Connect'],
    metrics: [
      { label: 'Qualified Inquiries', value: '+210%' },
      { label: 'Time on Page', value: '4m 32s' },
      { label: 'Direct Listings Sold', value: '₹150 Cr+' },
    ],
    heroImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&auto=format&fit=crop&q=80',
    desktopMockup: {
      heroTitle: 'Find Your Next Architectural Masterpiece',
      heroSubtitle: 'Exclusive modern residences, panoramic penthouses, and private estates across premier coastal destinations.',
      badge: 'Over ₹850 Cr+ in Premium Transactions',
      navItems: ['Properties', 'New Developments', 'Neighborhoods', 'Valuation', 'Contact'],
      ctaText: 'Explore Exclusive Listings',
      heroBg: 'bg-gradient-to-br from-cyan-950/70 via-slate-900 to-black',
      cards: [
        {
          title: 'The Azure Penthouse',
          desc: '4 Bed • 5 Bath • 4,800 sq ft with private infinity pool and 360° skyline vistas.',
          icon: 'Building',
          meta: '₹3.85 Cr',
        },
        {
          title: 'Villa Paradiso',
          desc: '6 Bed • 7 Bath • Direct private beachfront access, smart home automation.',
          icon: 'Compass',
          meta: '₹5.20 Cr',
        },
        {
          title: 'Free Property Valuation',
          desc: 'Get an accurate AI-assisted comparative market analysis in under 2 hours.',
          icon: 'TrendingUp',
          meta: 'Free Report',
        },
      ],
    },
  },
  {
    id: 'construction',
    title: 'SolidCraft Builders & Contractors',
    category: 'Construction & Renovations',
    tagline: 'Custom Residential Construction & Commercial Remodeling',
    description: 'Trust-building contractor website showcasing licensed credentials, high-res project galleries, verified client reviews, and instant estimate request forms.',
    accentColor: '#EAB308',
    gradient: 'from-yellow-500/20 via-amber-500/10 to-orange-500/20',
    features: ['Before & After Sliders', 'Online Project Estimator', 'Licensed & Insured Badge', 'Live WhatsApp Blueprint Chat'],
    metrics: [
      { label: 'Lead Conversion', value: '3.2x' },
      { label: 'Project Inquiries', value: '45+/mo' },
      { label: 'Local Search Visibility', value: '+300%' },
    ],
    heroImage: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1200&auto=format&fit=crop&q=80',
    desktopMockup: {
      heroTitle: 'Building Dreams on Unshakable Foundations',
      heroSubtitle: 'Licensed master builders delivering luxury custom homes, complete architectural renovations, and commercial developments.',
      badge: 'Licensed, Bonded & 25-Year Warranty',
      navItems: ['Projects', 'Services', 'Estimator', 'Warranty', 'Get Quote'],
      ctaText: 'Get Free Project Estimate',
      heroBg: 'bg-gradient-to-br from-stone-950 via-zinc-900 to-black',
      cards: [
        {
          title: 'Custom Luxury Homes',
          desc: 'End-to-end architectural design, permit management, and precision construction.',
          icon: 'Hammer',
          meta: '100% On Time',
        },
        {
          title: 'Full Home Remodeling',
          desc: 'High-end kitchen overhauls, spa master bathrooms, and open floor transformations.',
          icon: 'Layers',
          meta: 'Transparent Quotes',
        },
        {
          title: '25-Year Structural Warranty',
          desc: 'Every project is backed by our comprehensive guarantee and bonded coverage.',
          icon: 'ShieldCheck',
          meta: 'Guaranteed',
        },
      ],
    },
  },
  {
    id: 'coaching',
    title: 'Vanguard Executive Advisory',
    category: 'Personal Brand & Executive Coaching',
    tagline: 'High-Performance Leadership & Business Growth Advisory',
    description: 'An authoritative personal brand website positioning the expert, featuring media mentions, client case studies, podcast links, and strategy call booking calendar.',
    accentColor: '#8B5CF6',
    gradient: 'from-violet-500/20 via-purple-500/10 to-fuchsia-500/20',
    features: ['1-on-1 Strategy Call Booking', 'Video Case Study Vault', 'Lead Magnet PDF Downloads', 'Keynote Speaker Kit'],
    metrics: [
      { label: 'Client Discovery Calls', value: '+180%' },
      { label: 'Retainer Deals Closed', value: '₹75 Lakh+' },
      { label: 'Email Subscribers', value: '+4,200' },
    ],
    heroImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=1200&auto=format&fit=crop&q=80',
    desktopMockup: {
      heroTitle: 'Scaling Visionary Leaders from 7 to 8 Figures',
      heroSubtitle: 'Proven executive frameworks that streamline operations, elevate executive leadership, and unlock exponential enterprise value.',
      badge: 'Featured on Forbes, Inc. & TechCrunch',
      navItems: ['About', 'Framework', 'Client Results', 'Podcast', 'Apply'],
      ctaText: 'Apply for Private Advisory',
      heroBg: 'bg-gradient-to-br from-purple-950/70 via-slate-900 to-black',
      cards: [
        {
          title: 'CEO Mastermind Group',
          desc: 'Exclusive cohort of founders scaling high-growth tech & service companies.',
          icon: 'Users',
          meta: 'Quarterly Retreats',
        },
        {
          title: '1-on-1 Executive Advisory',
          desc: 'Bi-weekly strategic guidance on capital allocation, team culture, and CEO focus.',
          icon: 'Target',
          meta: 'Strictly 8 Clients',
        },
        {
          title: 'The Growth Playbook (Free)',
          desc: 'Download the 42-page blueprint used by 200+ venture-backed executives.',
          icon: 'BookOpen',
          meta: 'Instant Download',
        },
      ],
    },
  },
  {
    id: 'healthcare',
    title: 'Nova Dental & Implant Center',
    category: 'Healthcare & Dental Clinic',
    tagline: 'Modern Painless Dentistry & Cosmetic Smile Makeovers',
    description: 'A comforting, ultra-clean healthcare website providing doctor bios, smile makeover galleries, insurance checker, and 60-second online appointment scheduling.',
    accentColor: '#10B981',
    gradient: 'from-emerald-500/20 via-teal-500/10 to-cyan-500/20',
    features: ['Online Doctor Scheduling', 'Insurance & Financing Checker', 'Smile Gallery Before/After', 'Emergency Same-Day WhatsApp'],
    metrics: [
      { label: 'New Patient Registrations', value: '+240%' },
      { label: 'Emergency Calls', value: 'Instant' },
      { label: '5-Star Google Reviews', value: '450+' },
    ],
    heroImage: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=1200&auto=format&fit=crop&q=80',
    desktopMockup: {
      heroTitle: 'World-Class Gentle Dentistry for the Whole Family',
      heroSubtitle: 'State-of-the-art dental implants, cosmetic smile design, and painless pediatric care in a tranquil modern clinic.',
      badge: 'Accepting New Patients • 0% Financing Available',
      navItems: ['Treatments', 'Smile Gallery', 'Our Doctors', 'Insurance', 'Book Online'],
      ctaText: 'Schedule Consultation',
      heroBg: 'bg-gradient-to-br from-teal-950/70 via-slate-900 to-black',
      cards: [
        {
          title: 'All-on-4 Dental Implants',
          desc: 'Permanent natural teeth replacement in a single day with 3D digital planning.',
          icon: 'Activity',
          meta: 'Lifetime Warranty',
        },
        {
          title: 'Clear Invisalign Aligners',
          desc: 'Discreetly straighten your smile with customized clear aligners without metal.',
          icon: 'Smile',
          meta: 'From ₹2,499/mo',
        },
        {
          title: 'Emergency Dental Care',
          desc: 'Same-day emergency pain relief and gentle treatment for immediate comfort.',
          icon: 'Clock',
          meta: 'Same-Day Care',
        },
      ],
    },
  },
];
